// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhhUbcjjY8MEv2QGschYnxdPhH_XJ4q-I',
    appId: '1:47518243414:web:04ccf3fb9fb39e364a79f7',
    messagingSenderId: '47518243414',
    projectId: 'tdapp-f0ec3',
    authDomain: 'tdapp-f0ec3.firebaseapp.com',
    storageBucket: 'tdapp-f0ec3.appspot.com',
    measurementId: 'G-CF8Y65PDE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7tRrQt_97IjhEgbUn3q4mqm9C4ELMZVI',
    appId: '1:47518243414:android:fdbf5e8dc7762c334a79f7',
    messagingSenderId: '47518243414',
    projectId: 'tdapp-f0ec3',
    storageBucket: 'tdapp-f0ec3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9p_v5Y2tASzdytNYUyB8Lx9EKGRZ4TYY',
    appId: '1:47518243414:ios:1968ea3e115ba9204a79f7',
    messagingSenderId: '47518243414',
    projectId: 'tdapp-f0ec3',
    storageBucket: 'tdapp-f0ec3.appspot.com',
    iosClientId: '47518243414-mpn42kdkbmq7ipjhpnkajpbkenti0t95.apps.googleusercontent.com',
    iosBundleId: 'com.example.tdapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9p_v5Y2tASzdytNYUyB8Lx9EKGRZ4TYY',
    appId: '1:47518243414:ios:b6fb2507d4ccf7d14a79f7',
    messagingSenderId: '47518243414',
    projectId: 'tdapp-f0ec3',
    storageBucket: 'tdapp-f0ec3.appspot.com',
    iosClientId: '47518243414-gnkvdcdj9l2snrth1obslu969r6794j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tdapp.RunnerTests',
  );
}
